name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Swift packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.swiftpm
            ~/.xcode-deriveddata
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      - name: Build & Test
        run: |
          xcodebuild \
            -workspace WanderWise.xcworkspace \
            -scheme WanderWise \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            clean test \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
